# in .github/ranger.yaml
labels:
  accepted:
    action: close
    delay: 0s
    comment: "🎉 Your request was accepted, thank you for contributing!"
  duplicate:
    action: close
    delay: 0s
    comment: "⚠️ Your request has been removed for being a duplicate, next time please check if the domain/bug that you want to report was not already reported before creating a new one."
  rejected:
    action: close
    delay: 0s
    comment: "🚫 Your request was denied, please don't open an issue with the same domain/bug again! If you think there was an error, comment below and the issue will be reviewed again."
